# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yjb/Desktop/GPSpattern

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yjb/Desktop/GPSpattern

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yjb/Desktop/GPSpattern/CMakeFiles /home/yjb/Desktop/GPSpattern/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yjb/Desktop/GPSpattern/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GPSpattern

# Build rule for target.
GPSpattern: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GPSpattern
.PHONY : GPSpattern

# fast build rule for target.
GPSpattern/fast:
	$(MAKE) -f CMakeFiles/GPSpattern.dir/build.make CMakeFiles/GPSpattern.dir/build
.PHONY : GPSpattern/fast

gps_pattern.o: gps_pattern.cpp.o
.PHONY : gps_pattern.o

# target to build an object file
gps_pattern.cpp.o:
	$(MAKE) -f CMakeFiles/GPSpattern.dir/build.make CMakeFiles/GPSpattern.dir/gps_pattern.cpp.o
.PHONY : gps_pattern.cpp.o

gps_pattern.i: gps_pattern.cpp.i
.PHONY : gps_pattern.i

# target to preprocess a source file
gps_pattern.cpp.i:
	$(MAKE) -f CMakeFiles/GPSpattern.dir/build.make CMakeFiles/GPSpattern.dir/gps_pattern.cpp.i
.PHONY : gps_pattern.cpp.i

gps_pattern.s: gps_pattern.cpp.s
.PHONY : gps_pattern.s

# target to generate assembly for a file
gps_pattern.cpp.s:
	$(MAKE) -f CMakeFiles/GPSpattern.dir/build.make CMakeFiles/GPSpattern.dir/gps_pattern.cpp.s
.PHONY : gps_pattern.cpp.s

test.o: test.cpp.o
.PHONY : test.o

# target to build an object file
test.cpp.o:
	$(MAKE) -f CMakeFiles/GPSpattern.dir/build.make CMakeFiles/GPSpattern.dir/test.cpp.o
.PHONY : test.cpp.o

test.i: test.cpp.i
.PHONY : test.i

# target to preprocess a source file
test.cpp.i:
	$(MAKE) -f CMakeFiles/GPSpattern.dir/build.make CMakeFiles/GPSpattern.dir/test.cpp.i
.PHONY : test.cpp.i

test.s: test.cpp.s
.PHONY : test.s

# target to generate assembly for a file
test.cpp.s:
	$(MAKE) -f CMakeFiles/GPSpattern.dir/build.make CMakeFiles/GPSpattern.dir/test.cpp.s
.PHONY : test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... GPSpattern"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... gps_pattern.o"
	@echo "... gps_pattern.i"
	@echo "... gps_pattern.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

